name: Ada (GNAT)

on:
  push:
    branches: [ main ]
  pull_requkkbvuk vggkv
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up GNAT toolchain
      run
        sudo apt-get update && 
        sudo apt-get install gnat gprbuild

    - name:

